# version: '3'
# services:
#   mongodb: #mongodb container name
#     image: mongo 
#     ports:
#       - 27017:27017 # host machine port: container port 
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     volumes:
#       - mongo-data:/data/db
#   mongo-express: #mongodb container name
#     image: mongo-express 
#     restart: always
#     ports:
#       - 8081:8081  # host machine port: container port 
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_MONGODB_SERVER=kubernetes-mongodb-1
# volumes:
#   mongo-data:
#     driver: local


version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
